# AUTO-GENERATED by Phase 1.4 service extraction.
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional
import numpy as np
import soundfile as sf
import torch
from fastapi import File, HTTPException, Query, Request, UploadFile
from pydantic import BaseModel

from korina.runtime import state
from korina.util.paths import (
    ACK_DEFAULT_VOICE, ACK_PHRASES_PATH, ACK_DIR,
    LMSTUDIO_URL, LMSTUDIO_HUB_ROOT, LMSTUDIO_BIN,
    LLAMA_SERVER_BIN, LLAMA_SERVER_MEDIA_PATH, LLAMA_SERVER_USER_UNIT,
    WHISPER_MODEL_CHOICES, LOCAL_MODEL_ROOTS, WHISPER_MODEL_ID,
    WHISPER_DEVICE, WHISPER_COMPUTE_TYPE,
)

from korina.config import (
    load_config, save_config, synchronize_llm_dependents,
    config_tts_base_url, config_llm_base_url, config_llm_chat_url,
    config_stt_llm_provider, config_stt_llm_base_url, config_stt_llm_chat_url,
    config_stt_llm_api_env, config_stt_llm_model,
    agent_provider, agent_base_url, agent_chat_url, agent_models_url,
    agent_auth_headers,
)
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
import urllib.error
import urllib.request
import hashlib
import json
import base64
from korina.util.labels import safe_slug


from korina.runtime import (
    state,
)


def load_ack_manifest() -> list[dict]:
    """Read ack_phrases.json. Supports old list[str] format and new tagged format."""
    if not ACK_PHRASES_PATH.exists():
        return []
    data = json.loads(ACK_PHRASES_PATH.read_text())
    if isinstance(data, list):
        phrases = data
        return [
            {'id': f'ack_{i:02d}', 'text': str(text), 'tags': ['global']}
            for i, text in enumerate(phrases, start=1)
            if str(text).strip()
        ]
    raw_phrases = data.get('phrases', []) if isinstance(data, dict) else []
    out = []
    for i, item in enumerate(raw_phrases, start=1):
        if isinstance(item, str):
            text = item.strip()
            tags = ['global']
            ack_id = f'ack_{i:02d}'
        elif isinstance(item, dict):
            text = str(item.get('text', '')).strip()
            tags = item.get('tags') or ['global']
            if isinstance(tags, str):
                tags = [tags]
            tags = [safe_slug(str(t)) for t in tags if str(t).strip()] or ['global']
            ack_id = safe_slug(str(item.get('id') or text or f'ack_{i:02d}'))
        else:
            continue
        if text:
            out.append({'id': ack_id, 'text': text, 'tags': tags})
    return out

def ack_filename(voice: str, phrase: dict) -> str:
    digest = hashlib.sha1(f"{phrase['id']}|{phrase['text']}".encode('utf-8')).hexdigest()[:8]
    return f"{safe_slug(voice)}__{safe_slug(phrase['id'])}__{digest}.wav"

def ack_path(voice: str, phrase: dict) -> Path:
    return ACK_DIR / ack_filename(voice, phrase)

def ack_files_for(voice: str, tag: Optional[str] = None) -> list[dict]:
    ACK_DIR.mkdir(parents=True, exist_ok=True)
    requested_tag = safe_slug(tag or 'global')
    manifest = load_ack_manifest()
    matching = [p for p in manifest if requested_tag in p.get('tags', [])]
    if tag and not matching:
        matching = [p for p in manifest if 'global' in p.get('tags', [])]
    elif not tag:
        matching = [p for p in manifest if 'global' in p.get('tags', [])]
    files = []
    for phrase in matching:
        path = ack_path(voice, phrase)
        if path.exists() and path.stat().st_size > 44:
            files.append({
                'id': phrase['id'],
                'text': phrase['text'],
                'tags': phrase.get('tags', ['global']),
                'voice': voice,
                'name': path.name,
                'url': f'/Ack/{path.name}',
                'bytes': path.stat().st_size,
            })
    return files

def missing_ack_phrases(voice: str, tag: Optional[str] = None) -> list[dict]:
    requested_tag = safe_slug(tag) if tag else None
    manifest = load_ack_manifest()
    if requested_tag:
        manifest = [p for p in manifest if requested_tag in p.get('tags', [])]
    missing = []
    for phrase in manifest:
        path = ack_path(voice, phrase)
        if not path.exists() or path.stat().st_size <= 44:
            missing.append(phrase)
    return missing

def enqueue_missing_acks(voice: str, tag: Optional[str] = None) -> int:
    voice = (voice or ACK_DEFAULT_VOICE).strip() or ACK_DEFAULT_VOICE
    missing = missing_ack_phrases(voice, tag)
    with state.ack.queue_lock:
        existing = {(v, pid) for v, pid, _ in state.ack.queue} | set(state.ack.in_progress)
        added = 0
        for phrase in missing:
            key = (voice, phrase['id'])
            if key not in existing:
                state.ack.queue.append((voice, phrase['id'], phrase['text']))
                existing.add(key)
                added += 1
        if added and not state.ack.worker_running:
            state.ack.worker_running = True
            threading.Thread(target=ack_generation_worker, daemon=True).start()
    return len(missing)

def synthesize_ack_wav(voice: str, phrase_id: str, text: str) -> None:
    phrase = next((p for p in load_ack_manifest() if p['id'] == phrase_id), {'id': phrase_id, 'text': text, 'tags': ['global']})
    out = ack_path(voice, phrase)
    payload = json.dumps({'input': text, 'voice': voice, 'speed': 1.0, 'device': 'cpu'}).encode('utf-8')
    req = urllib.request.Request(
        f'{config_tts_base_url()}/v1/audio/speech',
        data=payload,
        headers={'Content-Type': 'application/json'},
        method='POST',
    )
    tmp = out.with_suffix('.tmp.wav')
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = resp.read()
    if len(data) <= 44:
        raise RuntimeError(f'generated ack for {phrase_id} was empty')
    tmp.write_bytes(data)
    tmp.replace(out)

def ack_generation_worker() -> None:
    try:
        while True:
            with state.ack.queue_lock:
                if not state.ack.queue:
                    state.ack.worker_running = False
                    return
                voice, phrase_id, text = state.ack.queue.pop(0)
                state.ack.in_progress.add((voice, phrase_id))
            try:
                synthesize_ack_wav(voice, phrase_id, text)
                state.ack.last_generated = f'{voice}:{phrase_id}'
                state.ack.last_error = None
                print(f'[acks] generated {state.ack.last_generated}', flush=True)
            except Exception as e:
                state.ack.last_error = f'{voice}:{phrase_id}: {e}'
                print(f'[acks] generation failed: {state.ack.last_error}', flush=True)
                time.sleep(2)
            finally:
                with state.ack.queue_lock:
                    state.ack.in_progress.discard((voice, phrase_id))
    finally:
        with state.ack.queue_lock:
            if not state.ack.queue:
                state.ack.worker_running = False

def clear_ack_wavs() -> int:
    count = 0
    for f in ACK_DIR.glob('*.wav'):
        try:
            f.unlink()
            count += 1
        except FileNotFoundError:
            pass
    return count

def ack_status(voice: str) -> dict:
    manifest = load_ack_manifest()
    generated = [p for p in manifest if ack_path(voice, p).exists() and ack_path(voice, p).stat().st_size > 44]
    with state.ack.queue_lock:
        queued = len(state.ack.queue)
        worker_running = state.ack.worker_running
    return {
        'voice': voice,
        'manifest_count': len(manifest),
        'generated_count': len(generated),
        'missing_count': len(missing_ack_phrases(voice)),
        'queue_depth': queued,
        'in_progress': [f'{v}:{pid}' for v, pid in sorted(state.ack.in_progress)],
        'generating': worker_running,
        'last_generated': state.ack.last_generated,
        'last_error': state.ack.last_error,
    }

