# AUTO-GENERATED by Phase 1.4 service extraction.
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional
import numpy as np
import soundfile as sf
import torch
from fastapi import File, HTTPException, Query, Request, UploadFile
from pydantic import BaseModel

from korina.runtime import state
from korina.util.paths import (
    ACK_DEFAULT_VOICE, ACK_PHRASES_PATH, ACK_DIR,
    LMSTUDIO_URL, LMSTUDIO_HUB_ROOT, LMSTUDIO_BIN,
    LLAMA_SERVER_BIN, LLAMA_SERVER_MEDIA_PATH, LLAMA_SERVER_USER_UNIT,
    WHISPER_MODEL_CHOICES, LOCAL_MODEL_ROOTS, WHISPER_MODEL_ID,
    WHISPER_DEVICE, WHISPER_COMPUTE_TYPE,
)

from korina.config import (
    load_config, save_config, synchronize_llm_dependents,
    config_tts_base_url, config_llm_base_url, config_llm_chat_url,
    config_stt_llm_provider, config_stt_llm_base_url, config_stt_llm_chat_url,
    config_stt_llm_api_env, config_stt_llm_model,
    agent_provider, agent_base_url, agent_chat_url, agent_models_url,
    agent_auth_headers,
    provider_preset_base_url, is_local_provider_base_url,
    display_model_label, parse_model_ids, agent_model_choices, llm_models_for,
)
import os
import re
import json



def local_model_roots() -> list[Path]:
    roots = list(LOCAL_MODEL_ROOTS)
    if LMSTUDIO_HUB_ROOT not in roots:
        roots.append(LMSTUDIO_HUB_ROOT)
    return roots

def discover_local_gguf_models() -> list[str]:
    found: set[str] = set()
    for root in local_model_roots():
        if not root.exists():
            continue
        for path in root.rglob('*.gguf'):
            lname = path.name.lower()
            if 'mmproj' in lname or lname.endswith('-assistant.gguf'):
                continue
            found.add(str(path))
    return sorted(found, key=lambda s: display_model_label(s).lower())

def discover_lmstudio_catalog_models() -> list[str]:
    found: set[str] = set()
    if LMSTUDIO_HUB_ROOT.exists():
        for manifest in LMSTUDIO_HUB_ROOT.rglob('manifest.json'):
            try:
                body = json.loads(manifest.read_text())
            except Exception:
                continue
            owner = body.get('owner')
            name = body.get('name')
            if isinstance(owner, str) and isinstance(name, str) and owner and name:
                found.add(f'{owner}/{name}')
    return sorted(found)

def find_mmproj_for_model(model_path: str) -> str:
    path = Path(str(model_path or '').strip())
    if not path.exists():
        return ''
    matches = sorted(path.parent.glob('*mmproj*.gguf'))
    return str(matches[0]) if matches else ''

