# AUTO-GENERATED by Phase 1.4 service extraction.
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional
import numpy as np
import soundfile as sf
import torch
from fastapi import File, HTTPException, Query, Request, UploadFile
from pydantic import BaseModel

from korina.runtime import state
from korina.util.paths import (
    ACK_DEFAULT_VOICE, ACK_PHRASES_PATH, ACK_DIR,
    LMSTUDIO_URL, LMSTUDIO_HUB_ROOT, LMSTUDIO_BIN,
    LLAMA_SERVER_BIN, LLAMA_SERVER_MEDIA_PATH, LLAMA_SERVER_USER_UNIT,
    WHISPER_MODEL_CHOICES, LOCAL_MODEL_ROOTS, WHISPER_MODEL_ID,
    WHISPER_DEVICE, WHISPER_COMPUTE_TYPE,
)

from korina.config import (
    load_config, save_config, synchronize_llm_dependents,
    config_tts_base_url, config_llm_base_url, config_llm_chat_url,
    config_stt_llm_provider, config_stt_llm_base_url, config_stt_llm_chat_url,
    config_stt_llm_api_env, config_stt_llm_model,
    agent_provider, agent_base_url, agent_chat_url, agent_models_url,
    agent_auth_headers,
    provider_preset_base_url, is_local_provider_base_url,
    display_model_label, parse_model_ids, agent_model_choices, llm_models_for,
)
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
import urllib.error
import urllib.request
import hashlib
import json
import base64
from korina.config import auth_headers_from_env, config_stt_llm_reasoning



def lmstudio_models() -> list[str]:
    config = load_config()
    return llm_models_for(config_llm_base_url(config), str(config.get('llm_api_key_env') or ''))

def lmstudio_transcribe_wav(wav: Path, *, model: Optional[str] = None, base_url: Optional[str] = None, api_env: Optional[str] = None) -> dict:
    """Attempt audio transcription through a multimodal STT model endpoint.

    OpenAI-compatible multimodal endpoints definitely support text/images. Audio input
    depends on the loaded model + server support, so this endpoint returns a clear
    error if the selected model rejects input_audio.
    """
    config = load_config()
    resolved_base_url = str(base_url or config_stt_llm_chat_url(config)).strip()
    resolved_api_env = str(api_env or config_stt_llm_api_env(config) or '').strip()
    selected_model = (model or config_stt_llm_model(config)).strip()
    if not selected_model:
        available = llm_models_for(config_stt_llm_base_url(config), resolved_api_env)
        selected_model = available[0].strip() if available else ''
    if not selected_model:
        raise RuntimeError('No multimodal STT model available for the selected endpoint')
    data = wav.read_bytes()
    b64 = base64.b64encode(data).decode('ascii')
    started = time.time()
    payload = {
        'model': selected_model,
        'messages': [
            {
                'role': 'system',
                'content': 'You are a strict speech-to-text engine. Return only the exact transcript. No commentary.',
            },
            {
                'role': 'user',
                'content': [
                    {'type': 'text', 'text': 'Transcribe this audio exactly. Return only the spoken words.'},
                    {'type': 'input_audio', 'input_audio': {'data': b64, 'format': 'wav'}},
                ],
            },
        ],
        'temperature': 0,
        'max_tokens': 512,
        'stream': False,
        'reasoning': config_stt_llm_reasoning(config),
    }
    headers = {'Content-Type': 'application/json'} | auth_headers_from_env(resolved_api_env)
    http_req = urllib.request.Request(
        resolved_base_url,
        data=json.dumps(payload).encode('utf-8'),
        headers=headers,
        method='POST',
    )
    try:
        with urllib.request.urlopen(http_req, timeout=120) as resp:
            body = json.loads(resp.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        detail = e.read().decode('utf-8', errors='replace')
        raise RuntimeError(
            f'Multimodal STT model {selected_model!r} rejected audio transcription request: HTTP {e.code}: {detail}'
        )
    text = (body.get('choices', [{}])[0].get('message', {}).get('content') or '').strip()
    return {
        'text': text,
        'seconds': time.time() - started,
        'model': selected_model,
        'backend': 'multimodal-stt',
        'segments': [{'start': None, 'end': None, 'text': text}] if text else [],
    }

